---
title: "Running"
output: rmarkdown::html_document
---

1. Get BRAF-targeted drugs, list records per indication

	`drugs <- oncoPharmaDB::get_onco_drugs(drug_is_targeted = T,
	drug_target = c('BRAF'))`

2. Get _approved_ BRAF-targeted drugs, list records per indication

	`drugs <- oncoPharmaDB::get_onco_drugs(drug_is_targeted = T,
	drug_target = c('BRAF'), drug_is_approved = T)`

3. Get BRAF-targeted drugs, list records per indication and drug synonym

	`drugs <- oncoPharmaDB::get_onco_drugs(drug_is_targeted = T,
	drug_target = c('BRAF'), list_per_drug_synonym = T)`

4. Get BRAF-targeted drugs, Open Targets Platform only, list per drug only

	`drugs <- oncoPharmaDB::get_onco_drugs(drug_is_targeted = T,
	drug_target = c('BRAF'), source_opentargets_only = T, output_resolution = "drug" )`
	
5. Get BRAF-targeted drugs, Open Targets Platform only, list per drug only, show key annotations only

	`drugs <- oncoPharmaDB::get_onco_drugs(drug_is_targeted = T,
	drug_target = c('BRAF'), source_opentargets_only = T, output_resolution = "drug",
	output_style = 'narrow')`
	

6. Get immune checkpoint inhibitors, list per drug-target entry

   `drugs <- oncoPharmaDB::get_onco_drugs(is_immune_checkpoint_inhibitor = T,
   output_resolution = "drug2target", output_style = "narrow")`
   
7. Get immune checkpoint inhibitors indicated for tumor subtypes within "Colon/Rectum", list per drug-target entry

   `drugs <- oncoPharmaDB::get_onco_drugs(is_immune_checkpoint_inhibitor = T,
   output_resolution = "drug2target", drug_indication_main = "Colon/Rectum", output_style = "narrow")`
   
8. Get antimetabolites

   `drugs <- oncoPharmaDB::get_onco_drugs(is_antimetabolite = T,
   output_resolution = "drug")`

